// Auto-generated by Sanity TypeGen — do not edit manually.
// Run `bun run update-types` in packages/sanity to regenerate.

export type InfoResult = {
  _id: string;
  _type: "info";
  text: string | null;
} | null;
